### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by gloparco** [MichMich/SwiftTextClock#4]
Very nice job on this clock!  I downloaded it from the App Store and it's great.

One suggestion, which I'm sure you've thought of already is to add the dots at the bottom of the clock, so that it can display the time more accurately.

Also, in future releases, the date and seconds functionality of the real watch would be intriguing to code.

Well done!

**Comment by MichMich** [comment]
Hi Gene,

These dots are still on my to-do list. Will add them in the future. :)

Cheers,

Vriendelijke groeten,

Michael Teeuw

	Michael Teeuw
Eigenaar Xonay Media
Xonay Media
Nieuwstraat 23B
3743 BK  Baarn	Tel: 035 887 57 07
Mobiel: 06 51 71 36 15
Email: michael@xonaymedia.nl
Web: xonaymedia.nl
Twitter: MichMich
Tumblr: michaelteeuw.nl



On 5 november 2015 at 16:31:27, Gene Loparco (notifications@github.com) wrote:

Very nice job on this clock! I downloaded it from the App Store and it's great.

One suggestion, which I'm sure you've thought of already is to add the dots at the bottom of the clock, so that it can display the time more accurately.

Also, in future releases, the date and seconds functionality of the real watch would be intriguing to code.

Well done!

**Comment by MichMich** [comment]
I've just submitted an update to the App Store which features the 4 dots. Stay tuned! :)

**Comment by MichMich** [comment]
This update is now available for download in the AppStore. :)
